#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
    echo "Error: Current directory is not \$WM_PROJECT_DIR/applications"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

wmake all utilities
wmake all solvers

if isMinGW; then
  #since we advise to build these in the wiki, lets just put them here to get built too
  wmake all utilities/mesh/conversion/Optional #ccmio26ToFoam
  wmake all test/parallel #parallelTest

  if [ ! -x "$WM_DIR/wmakeVerifyExeDependencies" ]; then chmod +x $WM_DIR/wmakeVerifyExeDependencies; fi

  wmakeVerifyExeDependencies utilities || wmake all utilities
  wmakeVerifyExeDependencies solvers || wmake all solvers
  
  wmake all utilities/mesh/conversion/Optional
  wmakeVerifyExeDependencies test/parallel || wmake all test/parallel #parallelTest
fi

# ----------------------------------------------------------------- end-of-file
