#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

[ -d "$WM_PROJECT_DIR" ] || {
    echo "Error: WM_PROJECT_DIR directory does not exist"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    echo "    WM_PROJECT_DIR=$WM_PROJECT_DIR"
    exit 1
}

set -x

rm -rf latex man qt_qch

# remove html directory in background
if [ -d "html" ]; then
  mv html html-stagedRemove$$ 2> /dev/null
  rm -rf html-stagedRemove$$ >/dev/null 2>&1 &
fi

# ensure that created files are readable by everyone
umask 22
if isMinGW; then
doxygen DoxyfileMinGWQt
cp -r css html/
cp *.png html/
else
doxygen
fi

# fix permissions (NB: '+X' and not '+x'!)
for folder in html latex man; do
  [ -d "$folder" ] && chmod -R a+rX $folder 2>/dev/null
done

echo
echo "Done doxygen"
echo

cp openfoam-code.qhcp qt_qch/
cd qt_qch
qcollectiongenerator openfoam-code.qhcp -o openfoam-code.qhc
cd ..

echo
echo "Done Qt collection generation."
echo

# ----------------------------------------------------------------- end-of-file
